@startuml universidade

title Matrícula de Universidade

class Aluno{
    - nome: String
    - cpf: Integer
    - telefone: Integer
    - data_nascimento: date
    - endereco: String
    + construtor (nome, matricula, data_nascimento, endereco)
}

class Disciplina{
    - nome: String
    - semestre: String
    - codigo_disciplina: int
    - carga_horaria: Float
    - turno: String
    - modalidade_disciplina: String
    - descricao: String
    - curso: Curso
    + construtor (nome, codigo_disciplina, carga_horaria, turno, modalidade_disciplina, descricao)
}

class Matricula{
    - codigo_matricula: int
    - tipo: String
    - data: date
    - aluno: aluno
    - disciplina: disciplina
    + construtor (codigo_matricula, tipo, data, aluno, disciplina)
}

class Curso{
    - nome: String  
    - codigo_curso: int
    - formacao: String
    - modalidade: String
    - duracao: String
    - area: Area
    + construtor (nome, codigo_curso, formacao, modalidade, duracao, area)
}

class Area{
    - nome: String
    - descricao: String
    - codigo_area: int
    + construtor (nome, descricao, codigo_area, )
}






Matricula *-- Aluno
Matricula *-- Disciplina
Disciplina *-- Curso
Curso *-- Area
Disciplina *-- Area

@enduml
