# Generated by Django 3.2.5 on 2022-06-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo da matricula')),
                ('tipo', models.TextField(max_length=50, verbose_name='Tipo')),
                ('data', models.TextField(max_length=50, verbose_name='Data')),
                ('aluno', models.TextField(max_length=50, verbose_name='alunos')),
                ('disciplina', models.TextField(max_length=50, verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'ordering': ['id'],
            },
        ),
    ]
