# Generated by Django 3.2.5 on 2022-06-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='codigod',
            field=models.CharField(default=1, max_length=10, verbose_name='CodigoD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='cursoss',
            field=models.CharField(default=1, max_length=10, verbose_name='Cursos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(default=1, max_length=50, verbose_name='Semestre'),
            preserve_default=False,
        ),
    ]
